setwd('~/Documents/projectos/manipulacao-e-visualizacao-de-dados-no-r/')
library(knitr)
library(markdown)
rm(list = ls())

knit('./rmds/01-instalacao-e-interface.Rmd')
knit('./rmds/02-estilo.Rmd')
knit('./rmds/03-objetos.Rmd')
knit('./rmds/04-arquivos.Rmd')
knit('./rmds/05-geracao-de-dados.Rmd')
knit('./rmds/06-graficos.Rmd')
knit('./rmds/07-estruturas-de-controle.Rmd')
knit('./rmds/08-estruturacao-de-bancos-de-dados.Rmd')
knit('./rmds/09-operacoes-em-bancos-de-dados.Rmd')
knit('./rmds/10-protocolo-de-exploracao-de-dados.Rmd')

setwd('~/Documents/projectos/manipulacao-e-visualizacao-de-dados-no-r/rmds/')
